BOSSES = (
    "Baldrix",
    "Black Mage",
    "First Adversary",
    "Jupiter",
    "Kaling",
    "Kalos",
    "Limbo",
    "Malefic Star",
    "Seren",
    "Lotus",
    "Damien",
    "Gloom",
    "Darknell",
    "Verus Hilla",
    "Slime",
    "Lucid",
    "Will",
)